<?php
// BRIDG site custom functions and utilities


function BRIDG_selection_about()  {

	$trail = menu_get_active_trail();
	$menuOne = $trail[1];
	if ( $menuOne['link_title'] == "About BRIDG Model") {
	  return true;
	} else {
	  return false;
	  
	}
}


function BRIDG_selection_download()  {

	$trail = menu_get_active_trail();
	$menuOne = $trail[1];
	if ( $menuOne['link_title'] == "Download/View Model") {
	  return true;
	} else {
	  return false;
	  
	}
}


function BRIDG_selection_contributing()  {

	$trail = menu_get_active_trail();
	$menuOne = $trail[1];
	if ( $menuOne['link_title'] == "Contributing to BRIDG") {
	  return true;
	} else {
	  return false;
	  
	}
}

function BRIDG_selection_provide_feedback()  {

	$trail = menu_get_active_trail();
	$menuOne = $trail[1];

	if ( $menuOne['link_title'] == "Providing Feedback") {
	  return true;
	} else {
	  return false;
	  
	}
}